### ISSUE TITLE
Can I use this without Composer ?

### ISSUE THREAD

**Issue by LioH** [markuspoerschke/iCal#101]
Where can I find the files ?
Thanks !

**Comment by soerenkk** [comment]
[Here](https://github.com/markuspoerschke/iCal/archive/master.zip)

However, doing that breaks the composer autoloader ([Line 3-4 in example 1](https://github.com/markuspoerschke/iCal/blob/master/examples/example1.php)), instead I use the following lines:

`spl_autoload_register(function ($name) {
	require_once(__DIR__ . '/' . str_replace('\\', DIRECTORY_SEPARATOR, $name) . '.php');
});
`
