### ISSUE TITLE
BYDAY recurrence as a string for more than one weekday?

### ISSUE THREAD

**Issue by wojlive** [markuspoerschke/iCal#105]
"""
BEGIN:VCALENDAR\r\n
VERSION:2.0\r\n
PRODID:User Events\r\n
BEGIN:VEVENT\r\n
UID:16\r\n
DTSTART:20170928T155500Z\r\n
SEQUENCE:0\r\n
TRANSP:OPAQUE\r\n
DTEND:20170928T155500Z\r\n
URL:Health & Well being\r\n
LOCATION:153\r\n
SUMMARY:Weekly event\r\n
CLASS:PUBLIC\r\n
DESCRIPTION:Gsfh\r\n
RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20171019T000000Z;BYDAY="TH,TH"\r\n
CATEGORIES:115\r\n
DTSTAMP:20170928T164855Z\r\n
END:VEVENT\r\n
END:VCALENDAR
"""

This causes Ical to be wrong as It should be BYDAY=TH,TH, without the quotes. how can that be solved?

**Comment by Idnan** [comment]
@markuspoerschke i am also getting the same issue. `"TH,TH"` shouldn't be escaped with `"`

**Comment by markuspoerschke** [comment]
Fix was released with `0.14.0`

**Comment by vody105** [comment]
@markuspoerschke I think you can close this issue
