### ISSUE TITLE
0.11.5 release tagged against wrong branch?

### ISSUE THREAD

**Issue by themightychris** [markuspoerschke/iCal#115]
It looks like the [0.11.5](https://github.com/markuspoerschke/iCal/releases/tag/0.11.5) release was tagged against the master branch instead of the 0.11.x branch

**Comment by markuspoerschke** [comment]
🤦‍♂️ you are right. I released `0.11.6` to overcome this problem.

https://packagist.org/packages/eluceo/ical#0.11.6

Thank you very much for this hint!! 👍
