### ISSUE TITLE
Document PHP version compatibility in release descriptions

### ISSUE THREAD

**Issue by themightychris** [markuspoerschke/iCal#116]
It took me some trial and error to figure out that the `0.11.x` branch and releases were the PHP5-compatible ones. Could a standard blurb in the descriptions for each release note each release's PHP version support?

**Comment by markuspoerschke** [comment]
I added a hint to the latest `0.11.x` release. (https://github.com/markuspoerschke/iCal/releases/tag/0.11.6)

I will stop maintaining the `0.11.x` branch anyhow, since there was enough time to update to PHP 7.
