### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by waveydavey0** [markuspoerschke/iCal#127]
Is there a feature / roadmap to import an existing Vcalendar data (text) file into your structure, parsing it correctly ?

**Comment by DerekFroese** [comment]
This would be very useful, if this could be used to combine ical files into a single ical file.

**Comment by ZacharyDuBois** [comment]
I am looking for exactly this. My work's scheduling software doesn't set alarms or metadata like location so I don't get nice features such as time to leave notifications. I'm looking for a library to both parse an existing feed and modify the events to re-output it.

**Comment by markuspoerschke** [comment]
This library is intendet to create iCal files only. It is currently not planned to add parsing.

If you need to parse iCal files, you might want to have a look at [sabre/vobject](https://sabre.io/vobject/icalendar/).

**Comment by ZacharyDuBois** [comment]
Thanks for the suggestion!
