### ISSUE TITLE
UID not unique with uniqid()

### ISSUE THREAD

**Issue by c33s** [markuspoerschke/iCal#129]
> The UID itself MUST be a globally unique identifier. The generator of the identifier MUST guarantee that the identifier is unique. 
https://www.kanzaki.com/docs/ical/uid.html

if events created in batch, `uniqueid()` creates identically ids for the events which is a bug.

> Warning: This function does not guarantee uniqueness of return value. Since most systems adjust system clock by NTP or like, system time is changed constantly. Therefore, it is possible that this function does not return unique ID for the process/thread. Use more_entropy to increase likelihood of uniqueness.
http://php.net/manual/en/function.uniqid.php

>A good method to assure uniqueness is to put the domain name or a domain literal IP address of the host on which the identifier was created on the right hand side of the "@", and on the left hand side, put a combination of the current calendar date and time of day (i.e., formatted in as a DATE-TIME value) along with some other currently unique (perhaps sequential) identifier available on the system (for example, a process id number). 
https://www.kanzaki.com/docs/ical/uid.html

solutions would be:
- make it a hard requirement to pass the uid in the constructor and remove the `uniqid()` function completly (very bad UX)
- quickfix as done in #70 (simply enhances the current situation)
- rebuild the uid as stated in the ical docs `uniqid("$_SERVER['REMOTE_ADDR']@...", true)`
- use https://packagist.org/packages/ramsey/uuid

**Comment by udf2457** [comment]
See #227

**Comment by markuspoerschke** [comment]
This have been finally solved with #277.

@udf2457 Thanks for your PR.
