### ISSUE TITLE
Possible bug with Immutable DateTime

### ISSUE THREAD

**Issue by Ali1** [markuspoerschke/iCal#133]
Calendar times were off by one hour when we hit British Standard Time. The app uses CakePHP which uses FrozenTime as it's main DateTime interface for model date-time data.

The line of code where the problem occurs is:
```
//DateUtil.php line 53
            $dateTime->setTimezone(new \DateTimeZone('UTC'));
// $dateTime is not modified
```

I've opted to `->toMutable()` the instance however just wanted to put this issue out there for anyone else searching.

Not sure whether you'd consider this a bug, but if so, the fix to make this library safe would be to either detect immutable classes at setDtStart/setDtEnd and throw an exception or to make ical immutable safe:
```
            $dateTime = $dateTime->setTimezone(new \DateTimeZone('UTC'));
// maybe more needs to be done?
```

**Comment by markuspoerschke** [comment]
This should be fixed with [Release 0.15.1](https://github.com/markuspoerschke/iCal/releases/tag/0.15.1).
