### ISSUE TITLE
How to parse iCal string

### ISSUE THREAD

**Issue by deepak-netwin** [markuspoerschke/iCal#138]
Hi,

I want to parse icalendar string.

e.g. I've below iCalendar string which I want to convert to php object:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:PortalSchani
BEGIN:VEVENT
UID:5d1488f60d363
DTSTART:20190726T183000Z
SEQUENCE:0
TRANSP:OPAQUE
DTEND:20500726T183000Z
SUMMARY:My birthday
CLASS:PUBLIC
DTSTAMP:20190627T091430Z
RRULE:FREQ=YEARLY;BYMONTH=7;BYMONTHDAY=26
END:VEVENT
END:VCALENDAR

**Comment by markuspoerschke** [comment]
This library can only create but not parse a iCal file. A popular package to parse iCal is [sabre/vobject](https://packagist.org/packages/sabre/vobject).
