### ISSUE TITLE
Special characters e.g. é in event text causes the ics file to not be generated correctly

### ISSUE THREAD

**Issue by mmodha** [markuspoerschke/iCal#140]
The ics file becomes invalid because the file will be shorted e.g. to 'END:VCALEND', this is because of special characters in the summary text. For each special character a letter will be removed.

**Comment by mmodha** [comment]
Hi any ideas when this issue can this be looked at. Thanks

**Comment by orditeck** [comment]
I don't experience this issue, I'm using special characters in calendar title, eg.:
```php
new \Eluceo\iCal\Component\Calendar("Exemple avec des èàù accents")
```
and events, eg.:
```php
(new \Eluceo\iCal\Component\Event())->setSummary("Résidus verts")
```

If I were you I'd look elsewhere, eg., setting the right headers:
```php
header('Content-Type: text/calendar; charset=utf-8');
```

**Comment by markuspoerschke** [comment]
@mmodha Can you check if the advice by @orditeck works?
