### ISSUE TITLE
How to make recurring event for first Monday of the month

### ISSUE THREAD

**Issue by ferremek** [markuspoerschke/iCal#151]
Hey guys,

First of all, thanks for creating this great package for creating iCalendars!

I am creating an calendar feed that pulls events from an API from a project management tool and I have one question regarding the recurring events. One thing I can't figure out is how to create an event that is on the first Monday of the month. Here is an example of a recurrence rule for an event like this: 

```php
$recurrenceRule = new RecurrenceRule();
$recurrenceRule->setFreq( RecurrenceRule::FREQ_MONTHLY );
$recurrenceRule->setByDay( 'MO' );
$recurrenceRule->setInterval( 1 );
```

The problem with this is that this event will show up on every Monday of every month. So my question is: _How can I show an event like this only on every first Monday of the month?_

Thanks in advance!

Cheers,
Ferre

**Comment by navarr** [comment]
You're missing `->setBySetPos(1)`

Using an RRULE generator like https://www.textmagic.com/free-tools/rrule-generator will help reveal which attributes you need to use.

**Comment by ferremek** [comment]
@navarr That's it, thanks for your quick response!

**Comment by markuspoerschke** [comment]
I close this issue because the question was answered.
