### ISSUE TITLE
Write UPGRADE-2.0.md guide

### ISSUE THREAD

**Issue by markuspoerschke** [markuspoerschke/iCal#166]
Explain how to upgrade from `0.*` version to the new `2.0` version of this package.

**Comment by tjveldhuizen** [comment]
The reference to the UPGRADE.md in https://github.com/markuspoerschke/iCal/releases/tag/2.0.0 is confusing me: while the release descript implicates I have to change things, the file doesn't mention any. Can you please clarify if this means that no changes are required, or they haven't been described, yet?

**Comment by markuspoerschke** [comment]
The upgrade guide was missing for `2.0.0`.

You can have a look at the current version here: https://github.com/markuspoerschke/iCal/blob/2.x/UPGRADE.md

I am happy about your feedback and if information are missing.
