### ISSUE TITLE
Import in google calendar now working

### ISSUE THREAD

**Issue by Xandar31** [markuspoerschke/iCal#215]
Hi,
I would like to generate a dynamic calendar that users can integrate into the google calendar via URL (https://domain/functions/ical/example1.php).

I've tried example1.php, but it doesn't appear there.
It works in Outlook, but not in Google Calendar. 

> BEGIN:VCALENDAR
> PRODID:-//eluceo/ical//2.0/EN
> VERSION:2.0
> CALSCALE:GREGORIAN
> BEGIN:VEVENT
> UID:6011131ee0d73
> DTSTAMP:20210127T071542Z
> SUMMARY:Christmas Eve
> DESCRIPTION:Lorem Ipsum Dolor...
> DTSTART:20210130T133000
> DTEND:20210130T143000
> BEGIN:VALARM
> ACTION:DISPLAY
> DESCRIPTION:Reminder: the meeting starts in 15 minutes!
> TRIGGER:RELATED=END:-PT15M
> END:VALARM
> END:VEVENT
> END:VCALENDAR

I just changed the date of the appointment to next Saturday

Does anyone have any idea why?
Regards

**Comment by markuspoerschke** [comment]
I suspect, that this can be related to #216. On the lint `TRIGGER:RELATED=END:-PT15M` is a syntax error. The first colon must be semicolon.

Maybe you can try again after #222 is merged and released.

**Comment by markuspoerschke** [comment]
@Xandar31 #222 is merged and released. Can you confirm whether the error still remains in version 2.1?

**Comment by Xandar31** [comment]
Hi @markuspoerschke , yes it's working now.
Many thanks for this,The tool helps me a lot
