### ISSUE TITLE
RFC 2445 is obsolete

### ISSUE THREAD

**Issue by cebe** [markuspoerschke/iCal#23]
I have not checked the details about what has changed but up to date iCal implementations should refer to RFC 5545 as far as I see.

http://www.ietf.org/rfc/rfc5545.txt

**Comment by Braunson** [comment]
:+1: Any potential updates to 5545?

**Comment by PowerKiKi** [comment]
The differences seems rather minor, according to [what is listed in RFC 5545](https://tools.ietf.org/html/rfc5545#appendix-A).

While it would be nice, and should not be a huge effort, to be compliant, I don't think it matters that much meanwhile...

**Comment by markuspoerschke** [comment]
As far as I could read the current feature set will support both. I will update the README.md so that we will follow RFC 5545 rather than 2445.

Thanks for this issue :smiley:

**Comment by markuspoerschke** [comment]
I will close this issue. README.md was changed. New features should follow RFC 5545 now!

**Comment by markuspoerschke** [comment]
Finally fixed by https://github.com/markuspoerschke/iCal/commit/1933a8c5b58b9c1c31bcf1d6a53d40d51ce85156

Thank you all for your participation in this project!
