### ISSUE TITLE
TZOFFSETTO and TZOFFSETFROM should never be -0000

### ISSUE THREAD

**Issue by JorisDebonnet** [markuspoerschke/iCal#245]
The standard does not allow -0000. In that case, it should be +0000.
https://icalendar.org/iCalendar-RFC-5545/3-3-14-utc-offset.html

To reproduce, you'll get the -0000 values when you try `$cal->addTimeZone(TimeZone::createFromPhpDateTimeZone( ... Europe/London ...)`

**Comment by markuspoerschke** [comment]
Thanks for reporting this bug.

It will be fixed in #246
