### ISSUE TITLE
Wrong parameter

### ISSUE THREAD

**Issue by garak** [markuspoerschke/iCal#281]
My code:
```php
$event = (new Event())
    ->setSummary('Foo')
    ->setDescription('Bar')
    ->setOccurrence(new SingleDay(new Date($myDateTime)))
;
$component = $this->calendarFactory->createCalendar(new Calendar([$event]));
```

when inspecting with phpstan, I get the following error (on last line):

>Parameter #<span></span>1 $events of class Eluceo\iCal\Domain\Entity\Calendar constructor expects                                                                                            
         (Eluceo\iCal\Domain\Collection\Events&iterable<Eluceo\iCal\Domain\Entity\Event>)|(iterable<Eluceo\iCal\Domain\Entity\Event>&Iterator<mixed, Eluceo\iCal\Domain\Entity\Event>),  
         array<int, Eluceo\iCal\Domain\Entity\Event> given.

**Comment by markuspoerschke** [comment]
Thanks for pointing this out. It was wrong indeed.

Be aware, that you might have to adopt your PHPStan config, once you update, because the muted error must be removed. Otherwise PHPStan might complain about a muted error that was never thrown.
