### ISSUE TITLE
install package conflicts with php 7.4?

### ISSUE THREAD

**Issue by hungdoviet** [markuspoerschke/iCal#309]
Problem 1
    - php 7.4.6 conflicts with eluceo/ical 2.2.0.
    - php 7.4.6 conflicts with eluceo/ical 2.x-dev.
    - php is present at version 7.4.6 and cannot be modified by Composer
    - Root composer.json requires eluceo/ical ^2.2 -> satisfiable by eluceo/ical[2.2.0, 2.x-dev].

what version should I install?
Thanks

**Comment by navarr** [comment]
7.4.0-7.4.5 or 7.4.7+

**Comment by hungdoviet** [comment]
Thanks, I changed php v and it is ok now

**Comment by markuspoerschke** [comment]
There is a bug in PHP 7.4.6 which makes this package fail. See #162.
