### ISSUE TITLE
Add attendee property

### ISSUE THREAD

**Issue by anubhav217** [markuspoerschke/iCal#315]

**Comment by ggiorginogrifo** [comment]
Dear @anubhav217, can you please close this issue? If you check the issue #190, you can see that there's already another issue that is same of your.
Thank you!

**Comment by giorginogreg** [comment]
Dear @anubhav217, can you please close this issue? If you check the issue #190, you can see that there's already another issue that is same of your.

Also, I'm working on that issue on a [public repo](https://github.com/giuseppenucifora/iCal/tree/feature/add-attendee), so if you want you can pm me and we can collaborate together!
Thank you!

**Comment by markuspoerschke** [comment]
Closed, because this issue duplicates #190
