### ISSUE TITLE
setOrganizer is not very useful

### ISSUE THREAD

**Issue by fsateler** [markuspoerschke/iCal#33]
The format for the organizer field is a bit weird, and this library doesn't quite support it.

**Comment by mikeminckler** [comment]
The proper format for ORGANIZER is
ORGANIZER;CN=John Doe:mailto:johndoe@example.com

**Comment by markuspoerschke** [comment]
This has been changed with: #42

**Comment by markuspoerschke** [comment]
Thanks for reporting!
