### ISSUE TITLE
The separator (semicolon) in Location (geo) is escaped in output

### ISSUE THREAD

**Issue by gbaudoin** [markuspoerschke/iCal#35]
So this gives geo:46.52028\;6.630208
Instead of geo:46.52028;6.630208
as per 3.8.1.6 in RFC 5545

**Comment by markuspoerschke** [comment]
Hey, 

I added an example on how to use it.

For me the following is working:

```
$vEvent->setLocation("Infinite Loop\nCupertino CA 95014", 'Infinite Loop', '37.332095,-122.030743');
```

There is a comma instead of a semicolon. I think we should use a PHP class there instead of a string to pass the Geo Code...
