### ISSUE TITLE
Add a .gitattributes to clean up vendor bundles

### ISSUE THREAD

**Issue by williamdes** [markuspoerschke/iCal#359]
There is quite a bunch of useless files that end up in production servers and workstations.
Please add a `.gitattributes` file, example: https://github.com/code-lts/doctum/blob/main/.gitattributes
```
bash-5.1# tree vendor/eluceo/
vendor/eluceo/
└── ical
    ├── Dockerfile
    ├── LICENSE
    ├── Makefile
    ├── composer.json
    ├── composer.lock
    ├── couscous.yml
    ├── dangerfile.js
    ├── infection.json
    ├── package.json
    ├── rulesets.xml
    ├── src (removed childs in this tree)
    └── yarn.lock

14 directories, 73 files
```

**Comment by navarr** [comment]
Is it better to use `.gitattributes` or composer's [`archive.exclude`](https://getcomposer.org/doc/04-schema.md#archive) here?

Or both?

**Comment by williamdes** [comment]
> Is it better to use `.gitattributes` or composer's [`archive.exclude`](https://getcomposer.org/doc/04-schema.md#archive) here?
> 
> Or both?

For having used both previous I would really recommend gitattributes
This will reflect on the `git archive` command

**Comment by williamdes** [comment]
Done in https://github.com/markuspoerschke/iCal/pull/510
Only `infection.json` is left
