### ISSUE TITLE
iCal as Symfony2 bundle with storable entities?

### ISSUE THREAD

**Issue by edrush** [markuspoerschke/iCal#39]
Hi,

I'm searching for an event library to include in a Symfony2 application. I'd like to store events in a database and be able to deliver them in iCalendar format - your package looks pretty good for this, right? Have there ever been thoughts to deliver it as a Symfony bundle? 
I'm thinking about doing so, to then add database mappings to your code to manage events in a database, while not messing up your code too much - what do you mean? Or do you know of existing implementations for that?

Best regards!

**Comment by Glifery** [comment]
@edrush maybe you have some progress in this direction?

**Comment by edrush** [comment]
@Glifery Hi, yes I built a bundle and we're currently using it in one of our projects. I'm about to release a first version in the next days, I'll let you know...

**Comment by edrush** [comment]
@Glifery Hi, so I gave my best and made a release of our ICalBundle that supports https://github.com/markuspoerschke/iCal, you'll find it here: https://github.com/xima-media/ical-bundle. It's my first Symfony bundle to be published, so please let me know if you have questions or something seems totally weird to you :)

**Comment by markuspoerschke** [comment]
Creating a Symfony Bundle to deal with calendar events will need to create a new project. At this point, this library will focus on generating iCal files only.

I will close this issue therefore.
