### ISSUE TITLE
If the description contains \r, they don't get stripped out or replaced.

### ISSUE THREAD

**Issue by thomwiggers** [markuspoerschke/iCal#43]
This breaks some iCal implementations such as http://severinghaus.org/projects/icv/ or ownCloud

example: http://rded.nl/test.ics

**Comment by markuspoerschke** [comment]
@thomwiggers I merged #36. Can you check if this fixes your problem?

**Comment by thomwiggers** [comment]
It replaces `\r`, so it would fix my problem. I'm currently unable to test this, but I'll just come back to this if it doesn't work (which seems quite unlikely).
