### ISSUE TITLE
Interest for a ICS parser ?

### ISSUE THREAD

**Issue by PowerKiKi** [markuspoerschke/iCal#45]
I am looking for an ICS lib that would allow me to read and write ICS files. Out of all projects I looked at, this one is definitely the most modern one and promising. But it unfortunately lacks a parser for my need. So the question is, **if** I was to implement a parser and submit a PR, would you accept it ? Or is it out of scope for this project ?

I usually quite like the idea to have model classes, and then separate Writer(s) and Reader(s) classes. This could allow, in the far future, for other writers ([ESS](http://essfeed.org/) ?).

But in this project the writer is "mixed" with the model. So the easiest way would probably be to add the missing getters for all ``Event``properties (and similar classes). And then implement ``Component::parse()`` for all components.

Some projects that could be used as inspiration for implementing the parser could be:

* https://github.com/iCalcreator/iCalcreator
* https://github.com/johngrogg/ics-parser
* https://github.com/endroid/Calendar

What do you think about that ? Is it worth investigating deeper ?

**Comment by tominon** [comment]
There is no need to reinvent the wheel. Check this library https://github.com/fruux/sabre-vobject

**Comment by PowerKiKi** [comment]
Great ! sabre-vobject looks amazing, thanks a lot !

... if you don't mind me asking, doesn't sabre-vobject make this project useless ? or would there be a need for for both projects to be used together ?

Closing this issue, since I'll very likely be using sabre-vobject.

**Comment by tominon** [comment]
I wouldn't call it "useless". It's a lightweight solution for creating iCal files only. If you need to parse and manipulate ICS files as well, go for sabre-vobject.

**Comment by PowerKiKi** [comment]
Thanks a lot for your advice, have a great week-end !
