### ISSUE TITLE
ORGANIZER does not support property parameters

### ISSUE THREAD

**Issue by troccoli** [markuspoerschke/iCal#46]
ORGANIZER, as ATTENDEE, supports parameters according to RFC2445. At the moment you can only set the value with `$vEvent->setOrganizer('mailto:giulio@troccoli.it')`, which is rendered as `ORGANIZER:mailto:giulio@troccoli.it`.

It would be nice if we could set parameters too, in a similar way as we for for attendees:

    $vEvent->setOrganizer('mailto:giulio@troccoli.it', ['CN' => 'Giulio Troccoli']);

which would be rendered as

    ORGANIZER;CN=Giulio Troccoli:mailto:giulio@troccoli.it

**Comment by markuspoerschke** [comment]
In version 0.9 the interface was changed. You have to pass now a ```Property\Oraganizer``` object. This should solve you issue?
