### ISSUE TITLE
iCal in one line

### ISSUE THREAD

**Issue by ogrosko** [markuspoerschke/iCal#469]
Hello 

iCal generates for me in one line and invalid to read by MacOS calendar looks like this

```BEGIN:VCALENDARPRODID:-//eluceo/ical//2.0/ENVERSION:2.0CALSCALE:GREGORIANBEGIN:VEVENTUID:79-639b2f86e6408DTSTAMP:20221215T143030ZSUMMARY:TestDTSTART:20230314END:VEVENTEND:VCALENDAR```

as soon as I add page breaks and file looks like this it works
```BEGIN:VCALENDAR
PRODID:-//eluceo/ical//2.0/EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:79-639b2d4fcbeda
DTSTAMP:20221215T142103Z
SUMMARY:Test
DTSTART:20230314
END:VEVENT
END:VCALENDAR```

Am I doing something wrong?

**Comment by markuspoerschke** [comment]
Hi @ogrosko, can you provide a minimal code example that is generating this output?

**Comment by ogrosko** [comment]
Hello @markuspoerschke 

Sorry, it was caused by wrong Response handling ...
