### ISSUE TITLE
cannot be downloaded on ios

### ISSUE THREAD

**Issue by irekasoft** [markuspoerschke/iCal#72]
the generated ics file cannot be downlaoded on ios only show the text

**Comment by markuspoerschke** [comment]
Do you send the correct HTTP headers? Maybe this question on Stackoverflow can help you?

http://stackoverflow.com/a/1464355

**Comment by wernerkrauss** [comment]
Same issue here, works on windows but not on mac. Running the file through a [validator](http://icalendar.org/validator.html) i get:


> Errors
> 
>     Lines not delimited by CRLF sequence near line # 1Reference: RFC 5545 3.1. Content Lines
