### ISSUE TITLE
Problem with GEO property when importing into Google Calendar

### ISSUE THREAD

**Issue by sgehrig** [markuspoerschke/iCal#73]
It seems as if the Google Calendar does not support the `GEO` property that was added with commit 7a3751f615fb4c53ccf174de7ff167f0b62da6b8 (this is also addressed in pull request #66). Importing an event with a `GEO` property fails in Google Calendar. 

There should be an option to disable the `GEO` property because setting the geo location works perfectly for iOS and Mac using the  `X-APPLE-STRUCTURED-LOCATION` property.

**Comment by sgehrig** [comment]
<img width="472" alt="bildschirmfoto 2016-06-01 um 13 00 04" src="https://cloud.githubusercontent.com/assets/43394/15707383/ca3e9f4a-27f8-11e6-933a-8e99fdb222d6.png">

**Comment by sgehrig** [comment]
The iCal used looks like:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:xxxxxx
CALSCALE:GREGORIAN
X-MICROSOFT-CALSCALE:GREGORIAN
X-PUBLISHED-TTL:P1W
BEGIN:VEVENT
UID:7fb3594c3ba12f47106f4122c650e7e99ac99e00
DTSTART:20160603T170000Z
SEQUENCE:3085364
TRANSP:TRANSPARENT
DTEND:20160603T190000Z
URL:https://example.com/event
LOCATION:Sporthalle Horkesgath\, Horkesgath 33\, 47803 Krefeld\, Deutschland
 d
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Sporthalle Horkesgath, Hor
 kesgath 33, 47803 Krefeld, Deutschland";X-APPLE-RADIUS=49;X-TITLE=Sporthal
 le Horkesgath / Krefeld:geo:51.33701\,6.52919
GEO:51.33701,6.52919
SUMMARY:Summary
CLASS:PUBLIC
CATEGORIES:Cat
DTSTAMP:20160601T072711Z
CREATED:20160601T072711Z
END:VEVENT
END:VCALENDAR
```

**Comment by sgehrig** [comment]
Just dug around a little bit and the problem is that [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.8.1.6) says that the **The value MUST be two SEMICOLON-separated FLOAT values.** while the library uses an escaped comma to separate lo latitude and longitude - it just reuses the `locationGeo` property that's being put into the Apple X-property.

**Comment by sgehrig** [comment]
Fixed with pull request #74 - can be closed.

**Comment by markuspoerschke** [comment]
Thanks for your contribution!

**Comment by dualitysol** [comment]
Does not work like this
