### ISSUE TITLE
GEO tag outputs wrong code?

### ISSUE THREAD

**Issue by jarofgreen** [markuspoerschke/iCal#79]
This seems wrong.

It outputs:

```
GEO:55.9527\;-3.20293
```

This does not validate, and I think the spec agrees on this: https://tools.ietf.org/html/rfc5545#section-3.8.1.6

If I edit the file to:

```
GEO:55.9527;-3.20293
```

It validates.

(I used http://severinghaus.org/projects/icv/ as a validator.)

ps. Also, is this a problem for:

```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Centotre, George Street, Edinburgh";X-APPLE-RADIUS=49;X-TITLE=Centotre:geo:55.9527\,-3.20293
```

**Comment by markuspoerschke** [comment]
@jarofgreen the fix is now available in master branch. Maybe you can have a look?
