### ISSUE TITLE
Events list?

### ISSUE THREAD

**Issue by usernameiswayne** [markuspoerschke/iCal#80]
Is there any list with all events or just the examples?

**Comment by kostcher** [comment]
``<?
$vCalendar = new \Eluceo\iCal\Component\Calendar('www.example.com');
$vEvent = new \Eluceo\iCal\Component\Event();
$vEvent
	->setDtStart(new \DateTime('2016-11-12'))
	->setDtEnd(new \DateTime('2016-11-13'))
	->setNoTime(true)
	->setSummary('NAME_EVENT1');


$vCalendar->addComponent($vEvent, 0);

$vEvent = new \Eluceo\iCal\Component\Event();
$vEvent
	->setDtStart(new \DateTime('2016-11-14'))
	->setDtEnd(new \DateTime('2016-11-16'))
	->setNoTime(true)
	->setSummary('NAME_EVENT2');

$vCalendar->addComponent($vEvent, 1);

$output = $vCalendar->render();
echo $output;
?>

**Comment by markuspoerschke** [comment]
I will close this ticket since there is no further activity on this ticket for month.

**Comment by devkiran** [comment]
@markuspoerschke  I have tried above method to add multiple events to components. But when I try validating the output using https://icalendar.org/validator.html, it is showing invalid. Do you have any idea about this error ?
