### ISSUE TITLE
DateTimesProperty should accept DateTimeInterface, not only DateTime

### ISSUE THREAD

**Issue by sc0rp10** [markuspoerschke/iCal#86]
Now constructor fails on `DateTimeImmutable`

**Comment by navarr** [comment]
Current minimum requirement is PHP 5.3

Usage of \DateTimeInterface will bump the minimum requirement to 5.5.0

**Comment by markuspoerschke** [comment]
I think since PHP 5.3 is no longer supported we should drop that support as soon as there are some more and bigger changes coming in. But for now I don’t see a reason to drop PHP 5.3 support only because of `\DateTimeInterface` usage.

**Comment by markuspoerschke** [comment]
The master branch requires PHP 7.0 now. Therefore I replaced all `\DateTime` code hintings with `\DateTimeInterface`.

@sc0rp10 thanks for your valuable input.
@navarr thanks for your support with this task! :)
