### ISSUE TITLE
setRecurrenceRuleAsString() ?

### ISSUE THREAD

**Issue by Ydalb** [markuspoerschke/iCal#90]
Hey !
First of all, nice work, very usefull ! :)

I think it could be nice to implement a setRecurrenceRuleAsString() function for those (like me :D) who has already the RRULE in string format.

I'll try to PR something, i'm not really familiar with this.

Regards,

**Comment by cmfcmf** [comment]
This looks like a duplicate of #37.

**Comment by Ydalb** [comment]
Oh i'm sorry, indeed ! Closing ticket :)
