### ISSUE TITLE
PHP Requirement confusion

### ISSUE THREAD

**Issue by jrjohnson** [markuspoerschke/iCal#91]
0.11.2 is marked as PHP 5 compatible, but there is PHP 7 only code:
https://github.com/markuspoerschke/iCal/blob/0.11.2/src/Property/Event/Geo.php
in at least that spot. `master` is marked as PHP 7+ so maybe just a tagging issue?

**Comment by markuspoerschke** [comment]
Actually true. But funily you can use it anyways because the classes are in the wrong folder. Let me fix that.

**Comment by markuspoerschke** [comment]
Versions `< 0.12` should be compatible with PHP 5.3. The compatibility for the older PHP versions was dropped in version `0.12`. I wanted to backport this fix but I wasn’t paying that much attention on testing. ;)

Thanks for creating this issue! 👍

**Comment by markuspoerschke** [comment]
I will tag a new Version of `0.11.*` tomorrow (my timezone is GMT+02).

**Comment by jrjohnson** [comment]
No problem - I was surprised it ran just fine - other than the PR I put in.  Thanks for the fix - no rush.

**Comment by markuspoerschke** [comment]
Tagged 0.11.3
