### ISSUE TITLE
Write more detailed documentation

### ISSUE THREAD

**Issue by markuspoerschke** [markuspoerschke/iCal#92]
A lot of aspects of this library aren’t documented very well.

* Currently the documentation is only a rough summary of the basic usage: creating simple ics files.
* There should be a more detailed explanation.
* Also the examples need more explanation.
* Maybe generated PHPDoc can be added.
* Full aspects of this issue are tbd.
* Some methods are confusing like https://github.com/markuspoerschke/iCal/pull/83#issuecomment-303032786 maybe also the API needs some change (not part of this issue of course)
* Some feature are not documented at all:
  * Attendees (See https://github.com/markuspoerschke/iCal/issues/97#issuecomment-304995599 for an quick explanation)

**Comment by dwenaus** [comment]
Yes please!

**Comment by markuspoerschke** [comment]
This will be done in Version 2.

The new documentation is already available on the new website: https://ical.poerschke.nrw/
