### ISSUE TITLE
Add Attendees

### ISSUE THREAD

**Issue by ajoudeh** [markuspoerschke/iCal#97]
Hi,

How i can add Attendees to ics. can you give the the code?

Thanks,

**Comment by markuspoerschke** [comment]
@navarr can you help here?

**Comment by navarr** [comment]
Hey @ajoudeh,

Once you have your iCal event component setup (like in the README), you can add Attendees to it like this:

`$vEvent->addAttendee($attendee)` where `$attendee` is a URI.  For example, you wanted to invite john@example.org, you would be able to simply do

`$vEvent->addAttendee('MAILTO:john@example.org')`

You may additionally specify a second parameter containing additional information, e.g.

`$vEvent->addAttendee('MAILTO:john@example.org', ['ROLE => 'REQ-PARTICIPANT'])`

The most important attributes and their values:

## Roles [ROLE]:
* CHAIR - Leader of the meeting
* REQ-PARTICIPANT - Someone required to be at the meeting
* OPT-PARTICIPANT - Optional Participant
* NON-PARTICIPANT - Someone copied on the meeting for information purposes only

## Participation Status [PARTSTAT]
* NEEDS-ACTION - If they have not yet responded
* ACCEPTED - If they have accepted the event
* DECLINED - If they have declined the event
* TENTATIVE - If they will tentatively show up
* DELEGATED - If they have sent someone in their place

## Common Name [CN]
This is used to send the name of the person along.  Your array might look like `['CN' => 'Navarr Barnier']`

**Comment by ajoudeh** [comment]
Thank you very much for your help.

**Comment by markuspoerschke** [comment]
@navarr Thanks for the detailed answer. I linked your comment in #92 so the information will not be lost when the documentation is written 👍 

I close this issue since the question was answered.
